// React/app/components/TodoForm.js
import React,{Component} from 'react';

/*
    给表单绑定vaue属性到状态state，必须同时提供修改函数onChange
*/

class TodoForm extends Component{
    constructor(){
        super();
        this.state = {
            keyword:'xxx'
        }

        this.handlerChange = this.handlerChange.bind(this);
        this.handlerAdd = this.handlerAdd.bind(this);
    }
    handlerChange(e){
        //    修改state状态值为输入框的内容
        this.setState({
            keyword:e.target.value
        })
    }
    handlerAdd(){
        this.props.handlerClick(this.state.keyword)
        this.setState({
            keyword:''
        },()=>{
            this.refs.keyword.focus();
        })
    }
    render(){
        
        return (
            <div className="input-group mb-3">
                <input 
                type="search" 
                className="form-control" 
                placeholder="Recipient's username" 
                value={this.state.keyword}
                onChange={this.handlerChange}
                ref="keyword"
                 />
                <div className="input-group-append">
                    <button className="btn btn-success" onClick={this.handlerAdd}>搜索</button>
                </div>
            </div>
        )
    }
}

export default TodoForm;

// Vue/app/TodoForm.vue
<template>
    <div class="input-group mb-3">
        <input type="search" ref="form" class="form-control" @keyup.13="add" v-model="text">
        <div class="input-group-append">
            <button class="btn btn-success" @click="add">添加</button>
        </div>
    </div>
</template>

<script>
// 暴露接口，用于其他模块的引入
let TodoForm = {
    data(){
        return {
            text:''
        }
    },
    methods:{
        add(){console.log(this.$refs)
            // console.log(6666)
            // this.handlerAdd({text:'xxx'})

            // 触发自定义事件：this.$emit(type,data)
            //  * type： 自定义事件名
            //  * data： 传输的数据

            this.$emit('additem',{
                text:this.text
            });

            // 清空并自动获得焦点
            this.text = '';
            this.$refs.form.focus();
        }
    },
    template:`#tempTodoForm`,

    mounted(){
        // 进入页面，自动获得焦点
        this.$refs.form.focus();
    }
}

export {TodoForm}

// 等效于 export let TodoForm = {}
</script>
