// React/app/components/TodoItem.js
import React from 'react';
// import React,{Component} from 'react';


// class TodoContent extends Component{

//     render(){
//         let {data,idx,handleRemove,handleComplete,handleSelect} = this.props;
//         return (
//             <tr className={data.completed?'table-success':''}>
//                 <td><input type="checkbox" checked={data.selected} onChange={()=>{handleSelect(idx)}}/></td>
//                 <td>{idx+1}</td>
//                 <td>{data.title}</td>
//                 <td>{data.completed ? '完成' : '待办'}</td>
//                 <td>
//                 <div className="btn-group btn-group-sm">
//                     <button className="btn btn-outline-success" onClick={()=>{handleComplete(idx)}}>完成</button>
//                     <button className="btn btn-outline-danger" onClick={()=>{handleRemove(idx)}}>删除</button>
//                 </div>
//                 </td>
//             </tr>
//         )
//     }
// }

import Button from './Button';

const TodoContent = ({data,idx,handleRemove,handleComplete,handleSelect})=>{
    return (
        <tr className={data.completed?'table-success':''}>
            <td><input type="checkbox" checked={data.selected} onChange={()=>{handleSelect(idx)}}/></td>
            <td>{idx+1}</td>
            <td>{data.title}</td>
            <td>{data.completed ? '完成' : '待办'}</td>
            <td>
            <div className="btn-group btn-group-sm">
                {/* <button className="btn btn-outline-success" onClick={()=>{handleComplete(idx)}}>完成</button>
                <button className="btn btn-outline-danger" onClick={()=>{handleRemove(idx)}}>删除</button> */}
                <Button className="btn btn-outline-success" handleClick={handleComplete.bind(this,idx)} text="完成"/>
                <Button className="btn btn-outline-danger" handleClick={handleRemove.bind(this,idx)} text="删除"/>
            </div>
            </td>
        </tr>
    )
}

export default TodoContent;

// Vue/app/components/TodoItem.vue
<template>
    <tr :class="{'table-success':data.done}" @click="select(!data.selected,idx)">
        <td><input type="checkbox" :checked="data.selected"></td>
        <td>{{idx+1}}</td>
        <td>{{data.text}}</td>
        <td>{{data.done ? '完成':'待办'}}</td>
        <td>
            <div class="btn-group btn-group-sm">
                <Button class="btn-outline-success" :handle-click="complete">完成</Button>
                <Button class="btn-outline-danger" :handle-click="remove">删除</Button>
                <!-- <button class="btn btn-outline-success" @click.stop="complete(idx)">完成</button>
                <button class="btn btn-outline-danger" @click.stop="remove(idx)">删除</button> -->
            </div>
        </td>
    </tr>
</template>

<script>
import bus from './bus';

import Button from './Button.vue';

// 暴露接口，用于其他模块的引入
export default {
    props:{
        data:Object,
        idx:[Number,String]
    },
    methods:{
        complete(){
            bus.$emit('completeitem',this.idx);
        },
        remove(){
            bus.$emit('removeitem',this.idx);
        },
        select(checked){
            bus.$emit('selectitem',checked,this.idx);
        }
    },
    components:{
        Button
    }
}
</script>
