// Vue/app/components/TodoContent.vue
<template>
    <table class="table">
        <thead>
            <tr>
            <th scope="col" width="80"><input type="checkbox" v-model="checkAll">全选</th>
            <th scope="col" width="50">#</th>
            <th scope="col" width="300">待处理事项</th>
            <th scope="col" width="80">状态</th>
            <th scope="col" width="100">操作</th>
            </tr>
        </thead>
        <tbody>
            <tr is="todo-item" v-for="(item,idx) in datalist" :key="item.id" :data="item" :idx="idx"></tr>
        </tbody>
    </table>
</template>

<script>
import bus from './bus';

// 引入todoItem
import TodoItem from './TodoItem.vue';

// 暴露接口，用于其他模块的引入
export default {
    props:{
        datalist:{
            type:Array,
            required:true
        }
    },
    data(){
        return {
            // checkAll:false
        }
    },
    computed:{
        checkAll:{
            get(){
                return this.datalist.every(item=>item.selected)
            },
            set(checked){
                bus.$emit('selectitem',checked);
            }
        }
    },
    components:{
        TodoItem
    }
}
</script>

// React/app/components/TodoContent.js
import React,{Component} from 'react';


import TodoItem from './TodoItem';

class TodoContent extends Component{

    render(){
        let {data,handleRemove,handleComplete,handleSelect} = this.props;
        return (
            <div>
                <table className="table">
                    <thead>
                        <tr>
                        <th scope="col"><input type="checkbox" checked={data.every(item=>item.selected)} onChange={handleSelect}/>全选</th>
                        <th scope="col">#</th>
                        <th scope="col">内容</th>
                        <th scope="col">是否完成</th>
                        <th scope="col">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {
                            data.map((item,idx)=><TodoItem 
                            data={item} 
                            idx={idx} 
                            key={idx}
                            handleRemove={handleRemove}
                            handleComplete={handleComplete}
                            handleSelect={handleSelect}
                            
                            />)
                        }
                    </tbody>
                    </table>
            </div>
        )
    }
}

export default TodoContent;
